//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyPADv5
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuenta()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int idCuenta { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<int> supago { get; set; }
        public Nullable<int> saldo { get; set; }
        public string estado { get; set; }
        public Nullable<int> concepto_idConcepto { get; set; }
        public Nullable<int> alumno_legajo { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual concepto concepto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
