//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyPADv5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int idPago { get; set; }
        public Nullable<int> supago { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cuenta_idCuenta { get; set; }
        public Nullable<int> alumno_legajo { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual cuenta cuenta { get; set; }
    }
}
